### ISSUE TITLE
AttributeError while running python runPROX2.py (test run)

### ISSUE THREAD

**Issue by kumarsaurabh20** [HassounLab/PROXIMAL2#1]
Hi,

I have come across an attribute error while performing a test run using all defaults `python runPROX2.py`. I have attached the error log file for your convenience. Let me know if you have any suggestions.

Thanks

best,
Kumar
[proxima_log.txt](https://github.com/HassounLab/PROXIMAL2/files/14334536/proxima_log.txt)

**Comment by sohahassoun** [comment]
Hi, i will have someone take a look at this and get back to you.




*Soha HassounProfessorDepartment of Computer ScienceTufts University*

*http://www.cs.tufts.edu/~soha* <http://www.cs.tufts.edu/~soha>

**Comment by sohahassoun** [comment]
Vlad writes:  Please reach out to him if you have further questions.

"Porokhin, Vladimir O." ***@***.***>


This is a common compatibility issue with networkx. I fixed this previously
by editing kcfconvoy files (e.g.
/Users/singh018/opt/anaconda3/envs/deep_ler/lib/python3.11/site-packages/kcfconvoy-0.0.5-py3.11.egg/kcfconvoy/Compound.py),
replacing instances of "self.graph.node" with "self.graph.nodes" in a few
places. I can't find my notes to confirm at the moment, but I believe this
is all that's needed.




*Soha HassounProfessorDepartment of Computer ScienceTufts University*

*http://www.cs.tufts.edu/~soha* <http://www.cs.tufts.edu/~soha>

**Comment by kumarsaurabh20** [comment]
Yes, changing the instances of self.graph.node solved the problem. Thanks for the prompt replies. 

best,
Kumar
